{
    "name": "EGP HR Employee",
    "version": "17.0.1.0.0",
    "summary": "EGP Human Resource Module",
    'sequence': -350,
    'category': 'Human Resources',
    "description": "",
    'depends': ['hr', 'mail', 'xlsx_reporting', 'hr_skills', 'gamification', 'egp_hr_org_structure',
                'maintenance'],
    'data': [
        # security files
        'security/egp_hr_security.xml',
        'security/ir.model.access.csv',

        # default Data Files.
        'data/egp_hr_employee_default_data.xml',
        'data/res_country_state_data.xml',
        'data/training_type_data.xml',
        'data/language_default_data.xml',
        'data/university_default_data.xml',
        'data/faculty_default_data.xml',
        'data/degree_default_data.xml',
        'data/major_default_data.xml',
        'data/district_default_data.xml',
        'data/step_default_data.xml',
        'data/organization_default_data.xml',
        'data/relationship_default_data.xml',
        'data/grade_default_data.xml',
        'data/religion_default_data.xml',
        'data/employee_retirement_cron.xml',
        'data/cron.xml',

        # Report pdf files
        'report/egp_hr_report_paper_format.xml',
        'report/egp_hr_employee_report.xml',
        'report/egp_hr_exclusive_report.xml',

        # xml view files
        'views/egp_hr_employee.xml',
        'views/egp_hr_criminal_record.xml',
        'views/egp_hr_print_action.xml',
        'views/egp_hr_resume.xml',
        'views/employee_search.xml',
        'views/egp_hr_retirement_views.xml',
        'views/egp_hr_fire_views.xml',
        'views/egp_hr_reward_views.xml',
        'views/egp_hr_punishment_views.xml',
        'views/egp_hr_appraisal_views.xml',
        'views/egp_hr_education_views.xml',
        'views/egp_hr_experience_views.xml',
        'views/egp_hr_promotion_views.xml',
        'views/egp_hr_exam_views.xml',
        'views/egp_hr_language_views.xml',
        'views/egp_hr_training_views.xml',
        'views/egp_hr_relative_views.xml',
        'views/egp_hr_publication_views.xml',
        'views/egp_hr_guarantee_views.xml',
        'views/egp_hr_travel_views.xml',
        'views/egp_hr_property_views.xml',
        'views/egp_hr_work_permit_views.xml',

        # wizard xml views
        'wizard/views/retirement_report_wizard_views.xml',
        'wizard/views/promotion_report_wizard_views.xml',
        'wizard/views/education_report_wizard_views.xml',
        'wizard/views/employee_report_wizard_views.xml',

        # Rpeort File views
        'wizard/report/report_action.xml',
        'wizard/report/report_paper_format.xml',
        'wizard/report/retirement_report_template.xml',
        'wizard/report/promotion_report_template.xml',
        'wizard/report/education_report_template.xml',
        'wizard/report/employee_report_template.xml',

    ],
    "assets": {
        'web.assets_backend': [
            # 'egp_hr/static/src/css/attachment_preview.css',
            'egp_hr/static/src/js/qcent_many2many_attachment_preview.js',
            'egp_hr/static/src/xml/qcent_many2many_attachment_preview_template.xml',
        ],
    },
    "author": "Nasratullah Shafiq",
    "website": "https://mcit.gov.af/",
    "installable": True,
    "application": True,
    "auto_install": False,
    "license": 'OPL-1',
}
